name: heart_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'   # (지금도 OK. Dart 3.x 포함. 나중에 원하면 '>=3.0.0 <4.0.0'로 올려도 됨)

dependencies:
  flutter:
    sdk: flutter

  
  english_words: ^4.0.0
  provider: ^6.0.5         
  
  shared_preferences: ^2.3.2
  flutter_colorpicker: ^1.0.3
  share_plus: ^10.0.2
  uuid: ^4.5.1
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
